initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.12.1
    volumeMounts:
      - mountPath: /target
        name: plugins

credentials:
  useSecret: true
  existingSecret: minio-credentials

configuration:
  defaultVolumesToFsBackup: true
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero
      config:
        region: minio
        s3ForcePathStyle: "true"
        s3Url: http://172.31.5.6:9000
  volumeSnapshotLocation: []

deployNodeAgent: true
snapshotsEnabled: false

schedules:
  argocd-daily:
    disabled: true
    schedule: "0 2 * * *"
    template:
      includedNamespaces:
        - argocd # select specific namespace which you want to backup it
      ttl: 168h


kubectl:
  image:
    registry: docker.io
    repository: bitnamilegacy/kubectl
    tag: "1.31"

