image:
  repository: velero/velero
  tag: v1.18.2   # make sure this matches the chart's default Velero version

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.12.1   # make sure it's compatible with the Velero version
    volumeMounts:
      - mountPath: /target
        name: plugins

credentials:
  useSecret: true
  existingSecret: cloud-credentials

configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero
      config:
        region: minio
        s3ForcePathStyle: "true"
        s3Url: http://172.31.5.6:9000   # set this to your MinIO URL/IP

  volumeSnapshotLocation: []   # MinIO has no native snapshot API

deployNodeAgent: true   # enables backing up Persistent Volume data
snapshotsEnabled: false
